name: Setup Environment ðŸ› ï¸

on:
  workflow_call:
    outputs:
      tag:
        description: "Get short hash commit"
        value: ${{ jobs.env.outputs.tag }}  
      repository:
        description: "Get repository name"
        value: ${{ jobs.env.outputs.repository }}          

jobs:
  env:
    name: Setup Environment ðŸ› ï¸
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.env.outputs.tag }}
      repository: ${{ steps.env.outputs.repository }}
    steps:
      - id: env
        run: |
          if [[ ! "$GITHUB_REF" =~ refs/tags ]]; then
            echo "tag=$(echo $GITHUB_SHA | cut -c 1-8)" >> $GITHUB_OUTPUT
          else
            echo "tag=$(echo $GITHUB_REF | cut -d / -f 3)" >> $GITHUB_OUTPUT
          fi
      - run: echo ${{ steps.env.outputs.tag }}
      - id: repository
        run: echo "repository=$(echo ${GITHUB_REPOSITORY} | aws -F'/' '{print$2}'" >> $GITHUB_OUTPUT