name: Terraform Validate and Lint ğŸ”

on:
  workflow_call:

jobs:
  terraform-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code ğŸ›’
        uses: actions/checkout@v4

      - name: Setup Terraform ğŸ”§
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.0.11

      - name: Initialize Terraform ğŸš€
        run: terraform init

      - name: Validate Terraform âœ…
        run: terraform validate

      - name: Lint Terraform ğŸ”
        run: terraform fmt -check
