name: Test Application ðŸ”¬

on:
  workflow_call:

jobs:
  test:
    name: Test Application ðŸ”Ž
    runs-on: ubuntu-latest
    needs:
      - vars
      - test
    steps:
      # need checkout before using compose-action
      - uses: actions/checkout@v3
      - uses: cloudposse/github-action-docker-compose-test-run@main
        with:
          file: ./docker-compose.yml
          service: test    