name: Trivy Scan ðŸ”’

on:
  workflow_call:

jobs:
  trivy:
    name: Trivy Scan ðŸ”’
    runs-on: ubuntu-latest
    needs:
      - build-and-push
    steps:
      - name: Run Trivy vulnerability scanner ðŸ”Ž
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/${{ GITHUB_REPOSITORY  }}:${{ needs.vars.outputs.tag }}
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security Tab ðŸ“ˆ
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'